#!/bin/bash
# This script starts the application on Linux (like .exe in windows)

# FIXED (FOR FEDORA) ON 02.04.2024 - BY DIND THIBAULT

# Unset OS Java-Paths
unset JAVA_HOME
unset JDK_HOME

export PATH="$(dirname "$0")/jre/bin:$PATH"

JAVA_NOT_FOUND_MSG="Aucun interpréteur Java n'a pu être trouvé sur la ligne de commande.
Merci d'installer Java à l'aide du gestionnaire de paquet de votre distribution,
ou sur http://www.java.com/fr/download"

classpath='lib/dvbern-lib-update.jar:lib/cryptutil.jar:lib/jaxb-api.jar:lib/activation.jar:lib/jaxb-impl.jar'

if [ ! -f ///$classpath ] ; then
	cd "$(dirname "$0")"
else
	cd //
fi

type java &> /dev/null
if [ "$?" -ne "0" ] ; then
        echo $JAVA_NOT_FOUND_MSG
        which zenity &> /dev/null && zenity --no-wrap --no-markup --warning --window-icon=error --text="$JAVA_NOT_FOUND_MSG"
        exit 1
fi

case "$(uname -i)" in
	i686|x86)
		libWebKitFile="/usr/lib32/libwebkit2gtk-4.0.so.37"		# PATH CORRECTION
		MY_LIBPATH="$(pwd)/lib/ubuntu/usr/lib/i386-linux-gnu"
	;;
	*)
		libWebKitFile="/usr/lib64/libwebkit2gtk-4.0.so.37"		# PATH CORRECTION
		MY_LIBPATH="$(pwd)/lib/ubuntu/usr/lib/x86_64-linux-gnu"
	;;
esac


if [ ! -f "${libWebKitFile}" ] ; then
		echo "LibWebKit2Gtk-4.0 Does not exist. Add it."

        export LD_LIBRARY_PATH="$LD_LIBRARY_PATH:${MY_LIBPATH}"
        echo "The LibWebKit2Gtk library path is $LD_LIBRARY_PATH"
        ls $MY_LIBPATH

        echo "If it is still not working, try: sudo apt-get install libwebkit2gtk-4.0-37 	<[ON UBUNTU/DEBIAN]"	# MODIFIED
	echo "Or, try: sudo dnf install webkit2gtk4.0 						<[ON FEDORA/RHEL]"	# ADDED
fi

java -cp $classpath ch.dvbern.lib.update.Launcher
